[package]
name = "thecodedmessage-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.49"

[[bin]]
name = "binary"
path = "src/binary.rs"

[[bin]]
name = "overflow"
path = "src/overflow.rs"
